[tool.poetry]
name = "awscleaner"
version = "0.1.0"
description = ""
authors = ["Lalit Mishra <gamewithlalit@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.26.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
